### ISSUE TITLE
Markers not showing when added in the same location

### ISSUE THREAD

**Issue by GreyOakSoftware** [lohanidamodar/flutter_google_maps#1]
I am currently facing an issue where I am using custom images as markers on my map, the trouble is when I add two markers with the same longitude and latitude one marker overlaps the other making the second one completely invisible, is there any way I could offset the markers so that they don't overlap one another.

**Comment by lohanidamodar** [comment]
I don't think there is a out of box way of doing that. Please check out this issue, might help you
https://github.com/johnpryan/flutter_map/issues/100
